# Generated by Django 6.1 on 2026-08-26 01:00

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(blank=True, max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('pdf', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='libros')),
                ('fecha_agregada', models.DateField(auto_now_add=True)),
                ('acceso_abierto', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Biblioteca Digital',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Parcial 1', 'Parcial 1'), ('Parcial 2', 'Parcial 2'), ('Parcial 3', 'Parcial 3'), ('Examen Final', 'Examen Final'), ('Trabajo', 'Trabajo')], max_length=20)),
                ('valor', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creditos_totales', models.IntegerField(default=120)),
            ],
            options={
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('codigo_verificacion', models.CharField(max_length=20, unique=True)),
                ('qr_code', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.carrera')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Certificados',
            },
        ),
        migrations.CreateModel(
            name='EntregaTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='entregas')),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Entregado', 'Entregado'), ('Calificado', 'Calificado'), ('Atrasado', 'Atrasado')], default='Entregado', max_length=20)),
                ('observacion', models.TextField(blank=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Entregas de Tareas',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('creditos', models.IntegerField(default=4)),
                ('descripcion', models.TextField(blank=True)),
                ('profesor', models.CharField(blank=True, max_length=100)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='plataforma.carrera')),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('Cursando', 'Cursando'), ('Aprobado', 'Aprobado'), ('Reprobado', 'Reprobado'), ('Retirado', 'Retirado')], default='Cursando', max_length=20)),
                ('nota_final', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('asistencia', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='plataforma.materia')),
            ],
            options={
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('numero_matricula', models.CharField(max_length=20, unique=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.carrera')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_estudiante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles de Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Períodos',
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField()),
                ('pdf_guia', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='guias')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='plataforma.materia')),
            ],
            options={
                'verbose_name_plural': 'Tareas',
            },
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.AlterModelOptions(
            name='mensaje',
            options={'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AddField(
            model_name='calificacion',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='plataforma.matricula'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='plataforma.periodo'),
        ),
        migrations.AddField(
            model_name='entregatarea',
            name='tarea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='plataforma.tarea'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'materia', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='entregatarea',
            unique_together={('tarea', 'estudiante')},
        ),
    ]
