# Generated by Django 6.1 on 2026-09-05 04:57

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_crear_usuario_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias', to='plataforma.perfildocente'),
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planificaciones', to='plataforma.perfildocente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='plataforma.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='plataforma.periodo')),
            ],
            options={
                'verbose_name_plural': 'Planificaciones',
                'ordering': ['-periodo__fecha_inicio', 'materia__codigo'],
                'unique_together': {('materia', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('peso_formativa', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('peso_practica', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('peso_examen', models.IntegerField(default=40, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parciales', to='plataforma.planificacion')),
            ],
            options={
                'verbose_name_plural': 'Parciales',
                'ordering': ['numero'],
                'unique_together': {('planificacion', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('tema', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('parcial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='plataforma.parcial')),
            ],
            options={
                'verbose_name_plural': 'Unidades',
                'ordering': ['numero'],
                'unique_together': {('parcial', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ActividadPlanificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('formativa', 'Formativa'), ('practica', 'Práctica'), ('examen', 'Examen')], default='formativa', max_length=20)),
                ('archivo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='planificacion')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_entrega', models.DateField()),
                ('permite_entrega_tardia', models.BooleanField(default=False)),
                ('fecha_limite_tardia', models.DateField(blank=True, null=True)),
                ('penalizacion_tardia', models.IntegerField(default=0, help_text='Porcentaje que se descuenta a las entregas fuera de plazo.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='plataforma.unidad')),
            ],
            options={
                'verbose_name_plural': 'Actividades Planificadas',
                'ordering': ['semana', 'id'],
            },
        ),
    ]
