# Generated by Django 6.1 on 2026-09-05 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_materia_docente_planificacion_parcial_unidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='actividad',
            field=models.ForeignKey(blank=True, help_text='Actividad de la planificación de la que cuelga. Define su categoría y su parcial.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='plataforma.actividadplanificada'),
        ),
    ]
