# Generated by Django 6.1 on 2026-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_matricular_sofia_perez'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificado',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Emitido', 'Emitido'), ('Rechazado', 'Rechazado')], default='Emitido', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='fecha_emision',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('matricula', 'Certificado de Matrícula'), ('notas', 'Certificado de Notas'), ('asistencia', 'Certificado de Asistencia')], max_length=50),
        ),
    ]
